export default{
  adopcion:[
    {
      foto:'images/1.jpg',
      nombre:'Zenit',
    },
    {
      foto:'images/2.jpg',
      nombre:'Pufy',
    },
    {
      foto:'images/3.jpg',
      nombre:'Sun',
    },
    {
      foto:'images/4.jpg',
      nombre:'Snow',
    },
    {
      foto:'images/5.jpg',
      nombre:'Sete',
    },
    {
      foto:'images/6.jpg',
      nombre:'Titi',
    },
    {
      foto:'images/7.jpg',
      nombre:'Calvin',
    },
    {
      foto:'images/8.jpg',
      nombre:'Moddy',
    },
    {
      foto:'images/9.jpg',
      nombre:'Turrón',
    },
    {
      foto:'images/10.jpg',
      nombre:'Xiki',
    },
    {
      foto:'images/11.jpg',
      title:'Urco',
    },
    {
      foto:'images/12.jpg',
      nombre:'Harry',
    },
  ]
}
